; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = firmware
default_envs = caixa


; =========================================================
; ESP32 PRINCIPAL - CAIXA
; =========================================================

[env:caixa]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

build_src_filter =
    +<caixa/>
    -<copo/>


; =========================================================
; ESP32-C3 - COPO
; =========================================================

[env:copo]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1

build_src_filter =
    +<copo/>
    -<caixa/>